FROM python

RUN mkdir -p /opt/igor/lib
WORKDIR /opt

RUN pip install --upgrade pip
RUN pip install psycopg2 redis psutil

COPY ./bin /opt/igor/bin
COPY ./ddl /opt/igor/ddl
COPY ./etc /opt/igor/etc
COPY ./lib/igor /opt/igor/lib/igor
COPY ./lib/pyigor /opt/igor/lib/pyigor

ENV PYTHONPATH=/opt/igor/lib

CMD ["python", "/opt/igor/bin/scheduler.py"]
