version: '3'

volumes:
  queue:
  database:

networks: 
  internal:
    internal: true

#
#  +---------------------------------------------------------+
#
#                               Igor
#
#    Internal Network
#
#             +--------------+        +--------------+
#             | Queue        |        | Database     |
#             | - redis      |        |  - postgres  |
#             |              |        |              |
#             |              |        |              |
#             | holds tasks  |        | primary data |
#             +------+---+---+        +-----+--+-----+
#                    |   |                  |  |
#                    |   |                  |  |
#                    |   +--------------+   |  |
#                    |                  |   |  |
#                    |   +------------/ | \-+  |
#                    |   |              |      |
#             +------+---+---+        +-+------+-----+
#             | Scheduler    |        | Daemon       |
#             |              |        |              |
#             |              |        |              |
#             |              |        |  worker(s)   |
#             | queues work  |        | (any number) |
#             +------+-------+        +-------+------+
#                    |                        |
#                    +------------+-----------+
#                                 |
#                          +------+-------+
#                          | Gateway      |
#                          |              |
# +----------------------- |              | ------------------+
#                          |              |
#  External Network        | api requests |
#                          +--------------+
#

services:
  # --- required data services ---
  queue:
    image: redis:latest # must be v5+
    ports:
      - 6379:6379
    volumes:
      - queue:/data
    networks:
        - internal

  database:
    image: docker.io/postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=igor
    volumes:
      - database:/var/lib/postgresql/data
    networks:
        - internal

  # --- igor internal services ---
  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile.scheduler
    environment:
      - IGOR_CONFIG=/opt/igor/etc/igor-docker.ini
      - IGOR_DEFAULT_ADMIN_USERS=admin:admin
    depends_on:
      - database
      - queue
    links:
      - database
      - queue
    networks:
        - internal

  daemon:
    build:
      context: ./
      dockerfile: Dockerfile.daemon
    environment:
      - IGOR_CONFIG=/opt/igor/etc/igor-docker.ini
    depends_on:
      - database
      - queue
    links:
      - database
      - queue
    networks:
        - internal

  # --- igor API gateway ---
  igor:
    build:
      context: ./
      dockerfile: Dockerfile.gateway
    ports:
      - 9025:9025
    environment:
      - IGOR_CONFIG=/opt/igor/etc/igor-docker.ini
    depends_on:
      - database
      - queue
      - daemon
      - scheduler
    links:
      - database
      - queue
    ports:
      - 9025:9025
    networks:
      - internal
      - default
